#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
#(on web-01 and web-02)

"server {
    server_name  .myserver.com
    location / {
        proxy_pass  http://mybackend;
        add_header  X-Upstream  03-web-01;
    }
}
"
