#!/usr/bin/env bash
#Install and configure HAproxy
#(on lb-01 server)
#Make sure that your servers are configured with the right hostnames:
#[STUDENT_ID]-web-01 and [STUDENT_ID]-web-

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.\*


#This makes sure that HAProxy can be managed via
#an init script
echo "ENABLED=1" > /etc/default/haproxy

#listen to web1 and web2 servers
echo "
    frontend http
        bind *:80
        default_backend servers
    
    backend servers
        balance roundrobin
        server 138269-web-01 54.87.169.56:80 check
        server 138269-web-02 18.234.192.161:80 check
    " >> /etc/haproxy/haproxy.cfg

#starts the service
service haproxy start
