#!/usr/bin/env bash
#A script that solves the problem why my Nginx installation is not listening to port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
/etc/init.d/nginx stop